openapi: 3.1.0
info:
  title: Students API
  summary: REST APIs for managing students in the system
  version: '1.0'
servers:
  - url: http://localhost:9000
    description: Local development environment
paths:
  /students:
    get:
      operationId: search-students
      description: API for searching students
      responses:
        200:
          description: Successfully retrived the students
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "/#/components/schemas/Student"
        401:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
        500:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
    post:
      operationId: add-student
      description: Add a new student in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "/#/components/schemas/Student"
      responses:
        200:
          description: Successfully saved the student
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Student"
        401:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
        500:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"

  /students/{id}:
    get:
      operationId: get-student
      description: Retrieve a single student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: firstName
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: Successfully retrived the student
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Student"
        401:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
        500:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
    put:
      operationId: update-student
      description: Update a student in the system
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "/#/components/schemas/Student"
      responses:
        200:
          description: Successfully saved the student
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Student"
        401:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
        500:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
    delete:
      operationId: delete-student
      description: Delete a single student
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Successfully deleted the student
        401:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
        500:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        gender:
          type: string
          enum:
            - Male
            - Female
            - Other
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string